# Generated by Django 4.2.6 on 2024-03-29 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_metadonneescarte_eleve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadonneescarte',
            name='autoevaluation_possible',
            field=models.CharField(choices=[(1, 'Facile'), (2, 'Moyen'), (3, 'Difficile'), (4, 'A Refaire immédiatement')], default=2, max_length=15),
        ),
        migrations.AlterField(
            model_name='metadonneescarte',
            name='phase',
            field=models.IntegerField(choices=[(0, 'Apprentissage'), (1, 'Approfondissement')], default=0),
        ),
    ]
