# Generated by Django 4.2.6 on 2024-03-29 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_metadonneescarte_autoevaluation_possible_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcarte',
            name='image_devant',
        ),
        migrations.RemoveField(
            model_name='flashcarte',
            name='image_dos',
        ),
    ]
