# Generated by Django 4.2.6 on 2024-03-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_flashcarte_image_devant_and_more'),
        ('compte', '0002_remove_deckutilisateur_cartes_deckutilisateur_cartes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deckutilisateur',
            name='cartes',
            field=models.ManyToManyField(to='quiz.metadonneescarte'),
        ),
    ]
