# Generated by Django 4.2.6 on 2024-03-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connaissance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='racine',
            field=models.BooleanField(default=True),
        ),
    ]
