# Generated by Django 4.2.6 on 2024-03-26 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connaissance', '0002_cours_racine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='parent',
            field=models.ForeignKey(blank=None, default=None, null=None, on_delete=django.db.models.deletion.CASCADE, to='connaissance.cours'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='racine',
            field=models.BooleanField(default=False),
        ),
    ]
