# Generated by Django 4.2.6 on 2024-03-26 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connaissance', '0003_alter_cours_parent_alter_cours_racine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=None, on_delete=django.db.models.deletion.CASCADE, to='connaissance.cours'),
        ),
    ]
